In [12]:
import numpy as np

# ARRAY

In [13]:
# Creating a 2D Array

arr = np.zeros((3,2))
print(arr)
print("===============================")
arr = np.full((3,3), None)
print(arr)
print("===============================")
arr = np.array([[1,2,3], [1,2,3], [1,2,3]])
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[None None None]
 [None None None]
 [None None None]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
# Matrix Add

arr_1 = np.array([[2, 2, 2],
                  [2, 2, 2],
                  [2, 2, 2]])

arr_2 = np.array([[1, 1, 1, 1],
                  [1, 1, 1, 1],
                  [1, 1, 1, 1]])

arr = np.zeros((len(arr_1), len(arr_1[0])))
for i in range(len(arr_1)):
    for j in range(len(arr_1[0])):
        arr[i][j] = arr_1[i][j] + arr_2[i][j]

print(arr)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [15]:
#Matrix Multiplication

arr = np.zeros((len(arr_1), len(arr_2[0])))

for i in range(len(arr_1)):
    for j in range(len(arr_2[0])):
        sum = 0
        for k in range(len(arr_1[0])):
            sum += arr_1[i][k] * arr_2[k][j]
        arr[i][j] = sum

print(arr)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [16]:
# 2D Array to Linear Array

arr_1 = np.array([[2, 2, 2],
                  [2, 2, 2],
                  [2, 2, 2]])

arr = np.array([0] * (len(arr_1) * len(arr_1[0])))

for i in range(len(arr_1)):
    for j in range(len(arr_1[0])):
        arr[len(arr_1[0]) * i + j] = arr_1[i][j]

print(arr)

[2 2 2 2 2 2 2 2 2]


# Linked List

In [17]:
# Node Class

class Node:
    def __init__(self, elem, next):
        self.elem = elem
        self.next = next

In [34]:
# Creating a Linked List

def createList(arr):
    head = Node(arr[0], None)
    tail = head
    for i in range(1, len(arr)):
        n = Node(arr[i], None)
        tail.next = n
        tail = tail.next
    
    return head

arr = [4, 5, 6, 8, 7]
head = createList(arr)

In [35]:
# Iteration 

def iteration(head):
    temp = head
    while temp != None:
        print(temp.elem)
        temp = temp.next

iteration(head)

4
5
6
8
7


In [ ]:
def 