In [4]:
# Matrix Add

import numpy as np

arr_1 = np.array([[2, 2, 2],
                  [2, 2, 2],
                  [2, 2, 2]])

arr_2 = np.array([[1, 1, 1, 1],
                  [1, 1, 1, 1],
                  [1, 1, 1, 1]])

arr = np.zeros((len(arr_1), len(arr_1[0])))
for i in range(len(arr_1)):
    for j in range(len(arr_1[0])):
        arr[i][j] = arr_1[i][j] + arr_2[i][j]

print(arr)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [9]:
#Matrix Multiplication

arr = np.zeros((len(arr_1), len(arr_2[0])))

for i in range(len(arr_1)):
    for j in range(len(arr_2[0])):
        sum = 0
        for k in range(len(arr_1[0])):
            sum += arr_1[i][k] * arr_2[k][j]
        arr[i][j] = sum

print(arr)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [17]:
# 2D Array to Linear Array

arr_1 = np.array([[2, 2, 2],
                  [2, 2, 2],
                  [2, 2, 2]])

arr = np.array([0] * (len(arr_1) * len(arr_1[0])))

for i in range(len(arr_1)):
    for j in range(len(arr_1[0])):
        arr[len(arr_1[0]) * i + j] = arr_1[i][j]

print(arr)

[2 2 2 2 2 2 2 2 2]
