In [5]:
import numpy as np

# ARRAY

In [13]:
# Creating a 2D Array

arr = np.zeros((3,2))
print(arr)
print("===============================")
arr = np.full((3,3), None)
print(arr)
print("===============================")
arr = np.array([[1,2,3], [1,2,3], [1,2,3]])
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[None None None]
 [None None None]
 [None None None]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
# Matrix Add

arr_1 = np.array([[2, 2, 2],
                  [2, 2, 2],
                  [2, 2, 2]])

arr_2 = np.array([[1, 1, 1, 1],
                  [1, 1, 1, 1],
                  [1, 1, 1, 1]])

arr = np.zeros((len(arr_1), len(arr_1[0])))
for i in range(len(arr_1)):
    for j in range(len(arr_1[0])):
        arr[i][j] = arr_1[i][j] + arr_2[i][j]

print(arr)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [15]:
#Matrix Multiplication

arr = np.zeros((len(arr_1), len(arr_2[0])))

for i in range(len(arr_1)):
    for j in range(len(arr_2[0])):
        sum = 0
        for k in range(len(arr_1[0])):
            sum += arr_1[i][k] * arr_2[k][j]
        arr[i][j] = sum

print(arr)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [16]:
# 2D Array to Linear Array

arr_1 = np.array([[2, 2, 2],
                  [2, 2, 2],
                  [2, 2, 2]])

arr = np.array([0] * (len(arr_1) * len(arr_1[0])))

for i in range(len(arr_1)):
    for j in range(len(arr_1[0])):
        arr[len(arr_1[0]) * i + j] = arr_1[i][j]

print(arr)

[2 2 2 2 2 2 2 2 2]


# Linked List

In [3]:
# Node Class

class Node:
    def __init__(self, elem, next):
        self.elem = elem
        self.next = next

In [4]:
# Creating a Linked List

def createList(arr):
    head = Node(arr[0], None)
    tail = head
    for i in range(1, len(arr)):
        node = Node(arr[i], None)
        tail.next = node
        tail = tail.next
    
    return head

arr = [1, 2, 3, 4, 5]
head = createList(arr)

In [5]:
# Iteration 

def printLinkedList(head):
    temp = head
    while temp != None:
        print(temp.elem, end = " ")
        temp = temp.next

printLinkedList(head)

1 2 3 4 5 

In [35]:
# Insert at Front

def insertAtFront(head, num):
    n = Node(num, head)
    head = n
    return head

head = insertAtFront(head, 0)
printLinkedList(head)

0 1 2 3 4 5 

In [ ]:
# Insert at End

def insertAtEnd(head, num, index):
    n = Node(num, None)
    
    

In [28]:
# Rotating a Linked List - Right

def Rotate_Right(head):
    second_lastNode = head
    lastNode = head.next
    while lastNode.next != None:
        lastNode = lastNode.next
        second_lastNode = second_lastNode.next
    
    lastNode.next = head
    second_lastNode.next = None
    head = lastNode
    return head

head = Rotate_Right(head)
printLinkedList(head)

5 1 2 3 4 

In [6]:
# Rotating a Linked List - Left

def Rotate_Left(head):
    second_Node = head.next
    lastNode = second_Node
    while lastNode.next != None:
        lastNode = lastNode.next

    lastNode.next = head
    head.next = None
    head = second_Node
    return head

printLinkedList(head)
head = Rotate_Left(head)
printLinkedList(head)
    


5 1 2 3 4 
1 2 3 4 5 


In [6]:
#Reversing a List in Place 

def reverseLinkedList(head):
    new_head = None
    temp = head
    while temp != None:
        secondNode = temp.next
        temp.next = new_head
        new_head = temp
        temp = secondNode

    head = new_head


reverseLinkedList(head)