# Quiz 1


In [1]:
# 1

def dotProduct(arr1, arr2):
    sum = 0
    for i in range(len(arr1)):
        sum += arr1[i] * arr2[i]
    
    return sum

arr1 = [1, 3, 5, 7]
arr2 = [2, 4, 6, 8]
dotproduct = dotProduct(arr1, arr2)
print(dotproduct)

100


In [3]:
#2 
import numpy as np


def transpose(arr):
    row, col = arr.shape
    new_arr = np.zeros((col, row), dtype = int)
    for i in range(row):
        for j in range(col):
            new_arr[j][i] = arr[i][j]

    return new_arr

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
newarr = transpose(arr)
print(newarr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
