# Quiz 1 Fall'23 (NAD)


In [1]:
# 1

def dotProduct(arr1, arr2):
    sum = 0
    for i in range(len(arr1)):
        sum += arr1[i] * arr2[i]
    
    return sum

arr1 = [1, 3, 5, 7]
arr2 = [2, 4, 6, 8]
dotproduct = dotProduct(arr1, arr2)
print(dotproduct)

100


In [3]:
#2 
import numpy as np


def transpose(arr):
    row, col = arr.shape
    new_arr = np.zeros((col, row), dtype = int)
    for i in range(row):
        for j in range(col):
            new_arr[j][i] = arr[i][j]

    return new_arr

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
newarr = transpose(arr)
print(newarr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Quiz 2 Fall'23 (NAD)

In [13]:
#Run this cell
class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next


def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head


def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()


In [4]:
def seperate(head):
    eh = Node(None, None)
    oh = Node(None, None)
    temp = head
    e_temp = eh
    o_temp = oh
    while temp != None:
        if temp.elem % 2 == 0:
            e_temp.elem = temp.elem
            e_temp.next = Node(None, None)
            e_temp = e_temp.next
        
        else:
            o_temp.elem = temp.elem
            o_temp.next = Node(None, None)
            o_temp = o_temp.next

        temp = temp.next

    return eh, oh

arr = [1, 5, 10, 6, 3, 4]
head = createList(arr)
print("Original Linked List: ", end = " ")
printLinkedList(head)

even, odd = seperate(head)
print("Even Linked List: ", end = " ")
printLinkedList(even)
print("Odd Linked List: ", end = " ")
printLinkedList(odd)



Original Linked List:  1-->5-->10-->6-->3-->4

Even Linked List:  10-->6-->4-->None

Odd Linked List:  1-->5-->3-->None



In [6]:
import numpy as np

In [12]:
# Question 1

def removeElement(arr, size, idx):
    for i in range(len(arr)):
        if i == idx:
            arr[i] == None
            rightShift(i, arr)


def rightShift(start, arr):
    for j in range(start, len(arr) - 1):
        rem = arr[j + 1]
        arr[j] = arr[j + 1]
        arr[j + 1] = rem


print("============Test 1==============")
arr = np.array([7, 12, 1, 2, 3, 5, None])
print(arr)
removeElement(arr, 6, 1)
print(arr)
print("============Test 2==============")
arr = np.array([1, 3, 75, 35, 30, 4, None])
print(arr)
removeElement(arr, 7, 4)
print(arr)


============Test 1==============
[7 12 1 2 3 5 None]
[7 1 2 3 5 None None]
============Test 2==============
[1 3 75 35 30 4 None]
[1 3 75 35 4 None None]


In [20]:
#Run this Cell
class Node:
    def __init__(self, e, n = None):
        self.elem = e
        self.next = n

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head


def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()

In [23]:
# Question 2

def increaes(head):
    temp = head
    while temp != None:
        temp.elem = temp.elem + 1
        temp = temp.next

    return head

arr = [2, 6, 4, 8]
head = createList(arr)
print("Original Linked List: ", end = " ")
printLinkedList(head)
increaes(head)
print("Modified Linked List: ", end = " ")
printLinkedList(head)

Original Linked List:  2-->6-->4-->8

Modified Linked List:  3-->7-->5-->9

